### ISSUE TITLE
pls share the webhook logic

### ISSUE THREAD

**Issue by priyara123** [actions-on-google/dialogflow-facts-about-google-nodejs#3]
where's the webhook logic being handled? I don't see any route for handling webhook post request from API.AI in the index.js. Could you pls add those details?

**Comment by nikitsharma15** [comment]
@priyara123 webhook need to be added under fulfillment section in api.ai and also you need to enable "use webhook" option under intent section too

**Comment by kshivanku** [comment]
@priyara123 this might help https://cloud.google.com/functions/docs/writing/http

**Comment by Canain** [comment]
Since we updated the sample, the incoming request handling can be found [here](https://github.com/actions-on-google/dialogflow-facts-about-google-nodejs/blob/master/functions/index.js#L270). It now uses Firebase Functions to host requests. We talk about Firebase functions in the readme and the Firebase Functions docs are [here](https://firebase.google.com/docs/functions/).

Closing this since we no longer use Cloud Functions directly.
