### ISSUE TITLE
Can't upload agent zip file to restore

### ISSUE THREAD

**Issue by khalilRhouma** [actions-on-google/dialogflow-facts-about-google-nodejs#30]
hello, 
I am trying to restore my agent from a backup zip file but when i click upload and select the zip file it won't upload the file.
![dialogflow](https://user-images.githubusercontent.com/35801846/56468692-154bae80-6430-11e9-81a5-37aa40a827c5.png)
as you see the window remain like that and don't progress for uploading.

**Comment by findzaatar** [comment]
You need to type RESTORE as the text box suggests and then you'll be able to select the Restore button. 

Closing due to no direct issue with the sample itself. This is a general question and is better suited for Stack Overflow -- Github issues are for reporting bugs contained in Actions on Google samples or client libraries, thank you for understanding.

**Comment by khalilRhouma** [comment]
ok, thank you fro your time

Le lun. 22 avr. 2019 à 23:53, Sarah Dwyer <notifications@github.com> a
écrit :

**Comment by mdaniel71** [comment]
thanks - awful UI though - why is greyed out?!
